### PR TITLE
v0.11.0

### LINKED ISSUE #134: Incorrect "since" time for total insulin
image

It appears that the time displayed for total insulin (normally for the day since approximately midnight) had a bug.

### PR DESCRIPTION
**Pull request by loudnate**
This version contains important safety fixes related to insulin interpretation:

- Boluses of 10 U or greater on x23+ pumps are not interpreted as primes (https://github.com/loudnate/LoopKit/issues/66)
- Empty reservoirs are not interpreted as no delivery (#142)

Additional improvements:
- Updating Amplitude SDK to [3.8.5](https://github.com/amplitude/Amplitude-iOS/releases/tag/v3.8.5)
- Updating LoopKit to [0.6.0](https://github.com/loudnate/LoopKit/releases/tag/v0.6.0) (Fixes #134)
- Max bolus and recommended bolus are available when using the bolus screen on watchOS

### CODE REVIEW

**Comment by sarahspins** [comment]
You are amazing @loudnate, thanks!

**Comment by sarahspins** [comment]
It looks like treatments and Loop info for the NS plugin are no longer being uploaded to NS with this update.. and I missing something?  The option switch is no longer there and I am not sure if that broke it :(

**Comment by jlucasvt** [comment]
I have been trying for weeks to "navigationBarHidden=True"...  Thank you for showing the way Nate

**Comment by loudnate** [comment]
@sarahspins you're no longer seeing treatments or loop status? So, nothing is uploading to Nightscout at all?

**Comment by sarahspins** [comment]
Nothing was getting uploaded to NS - I went back to 0.10.1 for now.

**Comment by loudnate** [comment]
Nothing should have changed for loop status upload in this release. If you try installing again, check that you are seeing entries in the Event History tab in the insulin data screen. They should show checkmarks when uploaded.

**Comment by sarahspins** [comment]
Looks like they're showing up in history, and with the checkmark showing they've been uploaded, but they're not showing up on NS...
img_0301
(chose this one because it was a high temp)
img_0300
NS shows only the previous zero temp over that time... it's as if it's just updating non-zero values :(
screen shot 2016-08-31 at 11 17 31 am

**Comment by loudnate** [comment]
OK I think what I'm hearing is that they are uploading (and you can see
them in your treatments.json endpoint or whatever) but they're not
rendering in the graph correctly anymore?

**Comment by sarahspins** [comment]
The non-0 values do not seem to be in treatments.json that I can see... only the 0 temps are in there (plus the .5 bolus I did to see if that would show up).  Everything that is older than these was from when I was still running 0.10.1 (prior to about 10:20 central time) so I didn't include it.

```
[  
   {  
      "_id":"57c706e9a0f1339b22e68a3c",
      "created_at":"2016-08-31T16:28:40Z",
      "eventType":"Correction Bolus",
      "unabsorbed":0,
      "timestamp":"2016-08-31T16:28:40Z",
      "enteredBy":"loop://Sarah's iPhone ",
      "insulin":0.5,
      "duration":0,
      "programmed":0.5,
      "type":"normal"
   },
   {  
      "_id":"57c6fea8a0f1339b22e686fd",
      "created_at":"2016-08-31T15:53:31Z",
      "temp":"absolute",
      "rate":0,
      "eventType":"Temp Basal",
      "timestamp":"2016-08-31T15:53:31Z",
      "enteredBy":"loop://Sarah's iPhone ",
      "duration":30,
      "absolute":0
   },
   {  
      "_id":"57c6f2fda0f1339b22e6823d",
      "created_at":"2016-08-31T15:03:41Z",
      "temp":"absolute",
      "rate":0,
      "eventType":"Temp Basal",
      "timestamp":"2016-08-31T15:03:41Z",
      "enteredBy":"loop://Sarah's iPhone ",
      "duration":30,
      "absolute":0
   },
```

**Comment by sarahspins** [comment]
I went back to 0.10.1 again and it updated all of the missing temp basal data.  Very concerning is that that what was being displayed on NS didn't even represent what was actually happening at all... which I suspected, based on what I was watching within Loop :(

on 0.11.0:
screen shot 2016-08-31 at 12 28 31 pm

back to 0.10.1:
screen shot 2016-08-31 at 12 30 43 pm

**Comment by loudnate** [comment]
@sarahspins if you get a chance, please give it another try.

**Comment by sarahspins** [comment]
Updated, built and running as of about 20 minutes ago.... but I am still not convinced that it's working as it should.  I will give it a little while longer and report back.

**Comment by sarahspins** [comment]
I'm neither convinced it's working as it should, or that it's not, but I've gone back to 0.10.1 for the night and I'll give it a better evaluation in the morning.

**Comment by sarahspins** [comment]
Seems to be working, though it seems to be not particularly reliable for real-time monitoring of what Loop is actually doing.. it seems that with the increased RF comms, many of them fail (I'm seeing this in the logs - but Loop is still running fine), in effect delaying the visibility of temp basals and such on NS.  Eventually it does seem to catch up.

**Comment by ps2** [comment]
I have been running this today, and have been watching the temp basal records in nightscout update, and they are updating reliably for me. 

They are lagged a bit (as they always have been, and as they are in OpenAPS), since they get fetched from history 5 minutes *after* they're enacted. 

Another thing I saw is that Riley has an emoji in her phone name. This build puts the phone name in a url in the 'enteredBy' attribute of treatments, which gives NS some troubles (it was sometimes displaying, sometimes not). I had to clean those entries out of my mongo db before NS would work properly.  If you think you are seeing this issue, open up the JS console on your NS site, and look for `Uncaught URIError: URI malformed` errors.

@sarahspins if you are seeing issues, could you note precisely what the inconsistency is and create a new ticket?  I.E. note what you see in NS, and in treatments.json, vs what you expect to see.

**Comment by sarahspins** [comment]
@ps2 since Nate's update yesterday it is in fact working well enough (it's just more delayed than I had become accustomed to) - prior to that it really wasn't working at all to upload any temp basals to NS, but that has been fixed.

**Comment by ps2** [comment]
I don't think we expecting any additional delays for getting temp basals uploaded with this update.  If you are seeing delays, could you file an issue?

**Comment by channemann** [comment]
image

The sharp drop at about 1pm on the basal chart corresponds to a zero-duration, zero temp being set to cancel the previous temp. From discussion with @loudnate, I believe this was fixed at some point previously, so perhaps it's either a reversion in Loopkit or building against the wrong branch.

**Pull request merged**
