### PR TITLE
Add x15 pumps to list of supported pump hardware

### PR DESCRIPTION
**Pull request by jlucasvt**
I added the x15 series of pumps to supported hardware list on Readme.md

### CODE REVIEW

**Comment by loudnate** [comment]
Has someone been successfully using this model with Loop?

**Comment by jlucasvt** [comment]
Yes

Sent from mobile
Jeremy Lucas
jlucasvt@gmail.com
404-314-7520

**Comment by jlucasvt** [comment]
@gera3d is using 515
@deedeemo_jr_twitter is using 515
https://gitter.im/loudnate/LoopKit?at=57c749ed928ae0e7346a0b98

**Comment by loudnate** [comment]
OK thanks. After confirming they are using it without issue (and able to fetch history, for example), can you re-open this against `dev`?

**Pull request closed without merging**
